name: Build Windows Artifacts
author: Minn

runs:
  using: composite
  steps:
    - name: Bootstrap vcpkg
      shell: cmd
      run: native/libdave/cpp/vcpkg/bootstrap-vcpkg.bat

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build Artifacts
      shell: bash
      run: ./gradlew build -Ptarget=x86_64-pc-windows-msvc
